In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path
from tqdm import tqdm
import numpy as np

In [2]:
# CONSTANTS:
# ALPHAS = [0.01, 0.025, 0.05, 0.1, 0.25, 0.5]
ALPHAS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]

# I should probably export the max_ind_set indices into a file so the selection is fixed and reproducible
# We should also fix our phenotype manifest so our arbitrary index is fixed

In [3]:
phenotype_manifest = pd.read_csv("phenotype_manifest.csv", usecols=[
    'description',
    'in_max_independent_set',
    'phenocode',
    'filename'
    ])

In [4]:
phenotype_manifest['description'] = phenotype_manifest['description'].fillna(phenotype_manifest['phenocode'])
max_ind_set = phenotype_manifest[phenotype_manifest['in_max_independent_set']]

In [5]:
exclude_phenotypes = []

In [6]:
with open("exclude_phenotypes.txt", "r") as file:
    for line in file:
        if line[0]=='#':
            continue
        exclude_phenotypes.append(int(line.strip().split()[0]))

In [7]:
expected_folders = []

for index, row in max_ind_set.iterrows():
    if index in exclude_phenotypes:
        expected_folders.append(np.nan)
    else:
        expected_folders.append(os.path.splitext(os.path.basename(row['filename']))[0])

In [8]:
metadata_columns = [
    "index",
    "description",
    "alpha",
    "dir_name",
    "num_snps_found",
    "num_coding_snps_found",
    "num_overlapping_snps",
    "num_overlapping_loci",
    "num_original_list",
    "num_original_coding_snps",
    "p_value_threshold",
    "percentage_loci_recovered",
    "ld_based_clumping",
    "r2_threshold",
    "kb_radius",
    "window_size"]
collected_metadata_df = pd.DataFrame(columns=metadata_columns)
collected_metadata_df['description'] = max_ind_set['description']
collected_metadata_df['index'] = max_ind_set.index
collected_metadata_df['dir_name'] = expected_folders
collected_metadata_df = collected_metadata_df.loc[collected_metadata_df.index.repeat(len(ALPHAS))].reset_index(drop=True)
collected_metadata_df['alpha'] = ALPHAS * len(max_ind_set)

In [14]:
collected_metadata_df

,index,description,alpha,dir_name,num_snps_found,num_coding_snps_found,num_overlapping_snps,num_overlapping_loci,num_original_list,num_original_coding_snps,p_value_threshold,percentage_loci_recovered,ld_based_clumping,r2_threshold,kb_radius,window_size
0,0,Albumin,0.5,biomarkers-30600-both_sexes-irnt.tsv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Albumin,1.0,biomarkers-30600-both_sexes-irnt.tsv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Albumin,1.5,biomarkers-30600-both_sexes-irnt.tsv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Albumin,2.0,biomarkers-30600-both_sexes-irnt.tsv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Albumin,2.5,biomarkers-30600-both_sexes-irnt.tsv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,7043,latanoprost,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,7043,latanoprost,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,7043,latanoprost,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,7043,latanoprost,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,7043,latanoprost,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
missing_indeces = []

for idx, row in collected_metadata_df.iterrows():
    alpha_folder = f"deepcast_sd_ablation/results_{str(row['alpha'])}"
    folder_path = f"{alpha_folder}/{row['dir_name']}"
    if not Path(folder_path):
        raise ValueError("No phecode directories found in 'patho_phenotypes/deepcast_phenotypes' folder")
    metadata_path = f"{folder_path}/metadata_df.csv"
    try:
        # Read the small single-row CSV
        temp_df = pd.read_csv(metadata_path)
        
        # Now update the corresponding fields in df1
        for col in temp_df.columns:
            if col in collected_metadata_df.columns:
                collected_metadata_df.at[idx, col] = temp_df.iloc[0][col]
                
    except FileNotFoundError:
        print(f"File {metadata_path} not found, skipping.")
        missing_indeces.append((idx, row['description'], row['alpha']))

File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/continuous-30100-both_sexes-irnt.tsv/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_0.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_1.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.0/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_2.5/nan/metadata_df.csv not found, skipping.
File deepcast_sd_ablation/results_3.0/nan/metadata_df.csv not found, skipping.

In [22]:
# excluded phenotypes
collected_metadata_df['num_snps_found'].isna().sum()

np.int64(85)

In [23]:
# timed out phenotypes
collected_metadata_df['dir_name'].isna().sum()

np.int64(84)

In [19]:
collected_metadata_df

,index,description,alpha,dir_name,num_snps_found,num_coding_snps_found,num_overlapping_snps,num_overlapping_loci,num_original_list,num_original_coding_snps,p_value_threshold,percentage_loci_recovered,ld_based_clumping,r2_threshold,kb_radius,window_size
0,0,Albumin,0.5,biomarkers-30600-both_sexes-irnt.tsv,870,173,419,949,975,103,0.0,0.973333,True,0.2,500,NaN
1,0,Albumin,1.0,biomarkers-30600-both_sexes-irnt.tsv,774,241,252,925,975,103,0.0,0.948718,True,0.2,500,NaN
2,0,Albumin,1.5,biomarkers-30600-both_sexes-irnt.tsv,712,289,186,907,975,103,0.0,0.930256,True,0.2,500,NaN
3,0,Albumin,2.0,biomarkers-30600-both_sexes-irnt.tsv,662,321,160,891,975,103,0.0,0.913846,True,0.2,500,NaN
4,0,Albumin,2.5,biomarkers-30600-both_sexes-irnt.tsv,626,352,137,872,975,103,0.000001,0.894359,True,0.2,500,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,7043,latanoprost,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,7043,latanoprost,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,7043,latanoprost,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,7043,latanoprost,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,7043,latanoprost,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
missing_indeces

[(150, 'Cereal type', 0.5),
 (151, 'Cereal type', 1.0),
 (152, 'Cereal type', 1.5),
 (153, 'Cereal type', 2.0),
 (154, 'Cereal type', 2.5),
 (155, 'Cereal type', 3.0),
 (294, 'Hearing difficulty/problems with background noise', 0.5),
 (295, 'Hearing difficulty/problems with background noise', 1.0),
 (296, 'Hearing difficulty/problems with background noise', 1.5),
 (297, 'Hearing difficulty/problems with background noise', 2.0),
 (298, 'Hearing difficulty/problems with background noise', 2.5),
 (299, 'Hearing difficulty/problems with background noise', 3.0),
 (324, 'Qualifications', 0.5),
 (325, 'Qualifications', 1.0),
 (326, 'Qualifications', 1.5),
 (327, 'Qualifications', 2.0),
 (328, 'Qualifications', 2.5),
 (329, 'Qualifications', 3.0),
 (330, 'Qualifications', 0.5),
 (331, 'Qualifications', 1.0),
 (332, 'Qualifications', 1.5),
 (333, 'Qualifications', 2.0),
 (334, 'Qualifications', 2.5),
 (335, 'Qualifications', 3.0),
 (336, 'Current employment status', 0.5),
 (337, 'Current employment status', 1.0),
 (338, 'Current employment status', 1.5),
 (339, 'Current employment status', 2.0),
 (340, 'Current employment status', 2.5),
 (341, 'Current employment status', 3.0),
 (384, 'Types of transport used (excluding work)', 0.5),
 (385, 'Types of transport used (excluding work)', 1.0),
 (386, 'Types of transport used (excluding work)', 1.5),
 (387, 'Types of transport used (excluding work)', 2.0),
 (388, 'Types of transport used (excluding work)', 2.5),
 (389, 'Types of transport used (excluding work)', 3.0),
 (420, 'Difference in mobile phone use compared to two years previously', 0.5),
 (421, 'Difference in mobile phone use compared to two years previously', 1.0),
 (422, 'Difference in mobile phone use compared to two years previously', 1.5),
 (423, 'Difference in mobile phone use compared to two years previously', 2.0),
 (424, 'Difference in mobile phone use compared to two years previously', 2.5),
 (425, 'Difference in mobile phone use compared to two years previously', 3.0),
 (540, 'Interpolated Year when operation took place', 0.5),
 (541, 'Interpolated Year when operation took place', 1.0),
 (542, 'Interpolated Year when operation took place', 1.5),
 (543, 'Interpolated Year when operation took place', 2.0),
 (544, 'Interpolated Year when operation took place', 2.5),
 (545, 'Interpolated Year when operation took place', 3.0),
 (558, 'Ever contemplated self-harm', 0.5),
 (559, 'Ever contemplated self-harm', 1.0),
 (560, 'Ever contemplated self-harm', 1.5),
 (561, 'Ever contemplated self-harm', 2.0),
 (562, 'Ever contemplated self-harm', 2.5),
 (563, 'Ever contemplated self-harm', 3.0),
 (636, 'Mean platelet (thrombocyte) volume', 0.5),
 (678, 'Number of correct matches in round', 0.5),
 (679, 'Number of correct matches in round', 1.0),
 (680, 'Number of correct matches in round', 1.5),
 (681, 'Number of correct matches in round', 2.0),
 (682, 'Number of correct matches in round', 2.5),
 (683, 'Number of correct matches in round', 3.0),
 (720, 'Number in household', 0.5),
 (721, 'Number in household', 1.0),
 (722, 'Number in household', 1.5),
 (723, 'Number in household', 2.0),
 (724, 'Number in household', 2.5),
 (725, 'Number in household', 3.0),
 (726, 'Number of vehicles in household', 0.5),
 (727, 'Number of vehicles in household', 1.0),
 (728, 'Number of vehicles in household', 1.5),
 (729, 'Number of vehicles in household', 2.0),
 (730, 'Number of vehicles in household', 2.5),
 (731, 'Number of vehicles in household', 3.0),
 (732, 'Average total household income before tax', 0.5),
 (733, 'Average total household income before tax', 1.0),
 (734, 'Average total household income before tax', 1.5),
 (735, 'Average total household income before tax', 2.0),
 (736, 'Average total household income before tax', 2.5),
 (737, 'Average total household income before tax', 3.0),
 (894, 'latanoprost', 0.5),
 (895, 'latanoprost', 1.0),
 (896, 'latanoprost', 1.5),
 (897, 'latanoprost', 2.0),
 (898, 'latanoprost', 2.5),
 (899, 'latanoprost', 3.0)]

In [28]:
collected_metadata_df.to_csv("collected_metadata.csv")